version: "3.8"
services:
  app:
    image: malle-react-app
    stdin_open: true # docker run -i
    tty: true 
    build: ./app
    ports:
      - "4000:3000"
    depends_on:
      - "api"
    volumes:
      - ./app/src:/usr/src/app/src
  api:
    image: malle-node-api
    build: ./api
    ports:
      - "5000:4000"
    depends_on:
      - "mongo"
    volumes:
      - ./api/src:/usr/src/api/src
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "2718:27017"
  adminmongo:
    image: adicom/admin-mongo
    ports:
      - "1234:1234"
